[package]
authors = ["Philip Daniels <Philip.Daniels1971@gmail.com>"]
edition = "2018"
name = "iterex"
version = "0.1.0"

[dependencies]
clap = "2.32"
lazy_static = "1.3"
dirs = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
